export const CATEGORIES = [
  'Teknoloji',
  'Beyaz Eşya',
  'Giyim & Moda',
  'Ayakkabı & Çanta',
  'Ev & Yaşam',
  'Mobilya & Dekorasyon',
  'Spor & Outdoor',
  'Kozmetik & Bakım',
  'Süpermarket',
  'Anne & Bebek',
  'Kitap & Kırtasiye',
  'Oyun & Oyuncak',
  'Seyahat',
  'Yemek & İçecek',
  'Sağlık',
  'Otomotiv',
  'Pet Shop',
  'Bahçe & Yapı',
];

export const CATEGORIES_WITH_OTHER = [...CATEGORIES, 'Diğer'];

// ── Exact-match map (case-insensitive key lookup) ─────────────────────────────
// Covers OnuAl site categories + common user-submitted variations.
const EXACT_MAP: Record<string, string> = {
  // ── Teknoloji ────────────────────────────────────────────────────
  'teknoloji': 'Teknoloji',
  'elektronik': 'Teknoloji',
  'cep telefonu': 'Teknoloji',
  'cep telefonu & aksesuar': 'Teknoloji',
  'telefon & aksesuar': 'Teknoloji',
  'telefon aksesuarı': 'Teknoloji',
  'telefon': 'Teknoloji',
  'bilgisayar': 'Teknoloji',
  'bilgisayar & tablet': 'Teknoloji',
  'bilgisayar & aksesuar': 'Teknoloji',
  'laptop & notebook': 'Teknoloji',
  'laptop': 'Teknoloji',
  'notebook': 'Teknoloji',
  'tablet': 'Teknoloji',
  'tv': 'Teknoloji',
  'televizyon': 'Teknoloji',
  'tv & ses sistemi': 'Teknoloji',
  'tv & ses sistemleri': 'Teknoloji',
  'tv & görüntü': 'Teknoloji',
  'tv & görüntü sistemleri': 'Teknoloji',
  'ses sistemi': 'Teknoloji',
  'kulaklık': 'Teknoloji',
  'foto & kamera': 'Teknoloji',
  'fotoğraf & kamera': 'Teknoloji',
  'kamera': 'Teknoloji',
  'drone': 'Teknoloji',
  'akıllı saat': 'Teknoloji',
  'akıllı saat & bileklik': 'Teknoloji',
  'yazıcı & tarayıcı': 'Teknoloji',
  'yazıcı': 'Teknoloji',
  'gaming': 'Teknoloji',
  'gaming & pc': 'Teknoloji',
  'pc & oyun': 'Teknoloji',
  'çevre birimleri': 'Teknoloji',
  'ağ & internet': 'Teknoloji',
  'router & modem': 'Teknoloji',
  'depolama': 'Teknoloji',
  'hard disk': 'Teknoloji',
  'monitör': 'Teknoloji',
  'klima': 'Teknoloji',
  // ── Beyaz Eşya ───────────────────────────────────────────────────
  'beyaz eşya': 'Beyaz Eşya',
  'büyük ev aletleri': 'Beyaz Eşya',
  'çamaşır makinesi': 'Beyaz Eşya',
  'bulaşık makinesi': 'Beyaz Eşya',
  'buzdolabı': 'Beyaz Eşya',
  'derin dondurucu': 'Beyaz Eşya',
  'fırın & ocak': 'Beyaz Eşya',
  'davlumbaz': 'Beyaz Eşya',
  'çamaşır kurutma': 'Beyaz Eşya',
  // ── Giyim & Moda ─────────────────────────────────────────────────
  'giyim': 'Giyim & Moda',
  'giyim & moda': 'Giyim & Moda',
  'giyim & aksesuar': 'Giyim & Moda',
  'kadın giyim': 'Giyim & Moda',
  'erkek giyim': 'Giyim & Moda',
  'çocuk giyim': 'Giyim & Moda',
  'bebek & çocuk giyim': 'Giyim & Moda',
  'moda': 'Giyim & Moda',
  'iç giyim': 'Giyim & Moda',
  'pijama': 'Giyim & Moda',
  'mayo & bikini': 'Giyim & Moda',
  'mayo & bikini & plaj': 'Giyim & Moda',
  'mont & kaban': 'Giyim & Moda',
  'ceket & mont': 'Giyim & Moda',
  'elbise & etek': 'Giyim & Moda',
  'gömlek & bluz': 'Giyim & Moda',
  'pantolon & şort': 'Giyim & Moda',
  'triko & kazak': 'Giyim & Moda',
  'eşofman': 'Giyim & Moda',
  'aksesuar': 'Giyim & Moda',
  'takı & aksesuar': 'Giyim & Moda',
  'saat': 'Giyim & Moda',
  'gözlük': 'Giyim & Moda',
  // ── Ayakkabı & Çanta ─────────────────────────────────────────────
  'ayakkabı': 'Ayakkabı & Çanta',
  'ayakkabı & çanta': 'Ayakkabı & Çanta',
  'kadın ayakkabı': 'Ayakkabı & Çanta',
  'erkek ayakkabı': 'Ayakkabı & Çanta',
  'çocuk ayakkabı': 'Ayakkabı & Çanta',
  'spor ayakkabı': 'Ayakkabı & Çanta',
  'bot & çizme': 'Ayakkabı & Çanta',
  'çanta': 'Ayakkabı & Çanta',
  'çanta & aksesuar': 'Ayakkabı & Çanta',
  'kadın çanta': 'Ayakkabı & Çanta',
  'sırt çantası': 'Ayakkabı & Çanta',
  'valiz & bavul': 'Ayakkabı & Çanta',
  'cüzdan': 'Ayakkabı & Çanta',
  // ── Ev & Yaşam ───────────────────────────────────────────────────
  'ev': 'Ev & Yaşam',
  'ev & yaşam': 'Ev & Yaşam',
  'ev, yaşam & mutfak': 'Ev & Yaşam',
  'ev yaşam': 'Ev & Yaşam',
  'ev ve yaşam': 'Ev & Yaşam',
  'mutfak': 'Ev & Yaşam',
  'mutfak & banyo': 'Ev & Yaşam',
  'küçük ev aletleri': 'Ev & Yaşam',
  'ev aletleri': 'Ev & Yaşam',
  'küçük mutfak aletleri': 'Ev & Yaşam',
  'temizlik': 'Ev & Yaşam',
  'temizlik ürünleri': 'Ev & Yaşam',
  'ev temizlik': 'Ev & Yaşam',
  'aydınlatma': 'Ev & Yaşam',
  'ev tekstili': 'Ev & Yaşam',
  'tekstil': 'Ev & Yaşam',
  'nevresim': 'Ev & Yaşam',
  'nevresim takımı': 'Ev & Yaşam',
  'perde & halı': 'Ev & Yaşam',
  'perde': 'Ev & Yaşam',
  'halı': 'Ev & Yaşam',
  'banyo': 'Ev & Yaşam',
  'banyo ürünleri': 'Ev & Yaşam',
  'depolama & düzenleme': 'Ev & Yaşam',
  'mutfak gereçleri': 'Ev & Yaşam',
  'pişirme & fırın': 'Ev & Yaşam',
  'sofra': 'Ev & Yaşam',
  'dekoratif ürünler': 'Ev & Yaşam',
  // ── Mobilya & Dekorasyon ─────────────────────────────────────────
  'mobilya': 'Mobilya & Dekorasyon',
  'mobilya & dekorasyon': 'Mobilya & Dekorasyon',
  'dekorasyon': 'Mobilya & Dekorasyon',
  'koltuk & kanepe': 'Mobilya & Dekorasyon',
  'yatak odası': 'Mobilya & Dekorasyon',
  'oturma odası': 'Mobilya & Dekorasyon',
  'masa & sandalye': 'Mobilya & Dekorasyon',
  'ofis mobilyası': 'Mobilya & Dekorasyon',
  'raf & kitaplık': 'Mobilya & Dekorasyon',
  // ── Spor & Outdoor ───────────────────────────────────────────────
  'spor': 'Spor & Outdoor',
  'spor & outdoor': 'Spor & Outdoor',
  'spor & fitness': 'Spor & Outdoor',
  'fitness': 'Spor & Outdoor',
  'fitness & spor': 'Spor & Outdoor',
  'outdoor': 'Spor & Outdoor',
  'kamp & doğa': 'Spor & Outdoor',
  'kamp': 'Spor & Outdoor',
  'bisiklet': 'Spor & Outdoor',
  'bisiklet & scooter': 'Spor & Outdoor',
  'koşu & yürüyüş': 'Spor & Outdoor',
  'futbol': 'Spor & Outdoor',
  'yüzme': 'Spor & Outdoor',
  'gym': 'Spor & Outdoor',
  // ── Kozmetik & Bakım ─────────────────────────────────────────────
  'kozmetik': 'Kozmetik & Bakım',
  'kozmetik & bakım': 'Kozmetik & Bakım',
  'kozmetik & kişisel bakım': 'Kozmetik & Bakım',
  'kişisel bakım': 'Kozmetik & Bakım',
  'parfüm': 'Kozmetik & Bakım',
  'parfüm & deodorant': 'Kozmetik & Bakım',
  'cilt bakımı': 'Kozmetik & Bakım',
  'yüz bakımı': 'Kozmetik & Bakım',
  'saç bakımı': 'Kozmetik & Bakım',
  'saç': 'Kozmetik & Bakım',
  'makyaj': 'Kozmetik & Bakım',
  'güneş ürünleri': 'Kozmetik & Bakım',
  'erkek bakım': 'Kozmetik & Bakım',
  'tıraş': 'Kozmetik & Bakım',
  'elektrikli bakım': 'Kozmetik & Bakım',
  // ── Süpermarket ──────────────────────────────────────────────────
  'süpermarket': 'Süpermarket',
  'market': 'Süpermarket',
  'gıda': 'Süpermarket',
  'gıda & içecek': 'Süpermarket',
  'atıştırmalık': 'Süpermarket',
  'içecek': 'Süpermarket',
  'kahve & çay': 'Süpermarket',
  'organik ürünler': 'Süpermarket',
  'aktüel ürünler': 'Süpermarket',
  // ── Anne & Bebek ─────────────────────────────────────────────────
  'bebek': 'Anne & Bebek',
  'anne & bebek': 'Anne & Bebek',
  'anne bebek': 'Anne & Bebek',
  'bebek & çocuk': 'Anne & Bebek',
  'çocuk': 'Anne & Bebek',
  'bebek giyim': 'Anne & Bebek',
  'bebek bakım': 'Anne & Bebek',
  'bebek arabası': 'Anne & Bebek',
  'bebek ürünleri': 'Anne & Bebek',
  // ── Kitap & Kırtasiye ────────────────────────────────────────────
  'kitap': 'Kitap & Kırtasiye',
  'kitap & kırtasiye': 'Kitap & Kırtasiye',
  'kırtasiye': 'Kitap & Kırtasiye',
  'kitap & dergi': 'Kitap & Kırtasiye',
  'hobi & koleksiyon': 'Kitap & Kırtasiye',
  'müzik aleti': 'Kitap & Kırtasiye',
  'müzik': 'Kitap & Kırtasiye',
  'sanat malzemeleri': 'Kitap & Kırtasiye',
  // ── Oyun & Oyuncak ───────────────────────────────────────────────
  'oyuncak': 'Oyun & Oyuncak',
  'oyun & oyuncak': 'Oyun & Oyuncak',
  'oyun': 'Oyun & Oyuncak',
  'oyun konsolu': 'Oyun & Oyuncak',
  'konsol oyun': 'Oyun & Oyuncak',
  'playstation': 'Oyun & Oyuncak',
  'xbox': 'Oyun & Oyuncak',
  'nintendo': 'Oyun & Oyuncak',
  'pc oyun': 'Oyun & Oyuncak',
  'lego': 'Oyun & Oyuncak',
  // ── Seyahat ──────────────────────────────────────────────────────
  'seyahat': 'Seyahat',
  'seyahat & turizm': 'Seyahat',
  'uçak bileti': 'Seyahat',
  'otel': 'Seyahat',
  'tatil': 'Seyahat',
  'tur': 'Seyahat',
  'vize': 'Seyahat',
  // ── Yemek & İçecek ───────────────────────────────────────────────
  'yemek': 'Yemek & İçecek',
  'yemek & içecek': 'Yemek & İçecek',
  'restoran': 'Yemek & İçecek',
  'fast food': 'Yemek & İçecek',
  'kafe': 'Yemek & İçecek',
  'pizza': 'Yemek & İçecek',
  'paket servis': 'Yemek & İçecek',
  'yemek siparişi': 'Yemek & İçecek',
  // ── Sağlık ───────────────────────────────────────────────────────
  'sağlık': 'Sağlık',
  'sağlık & güzellik': 'Sağlık',
  'vitamin & takviye': 'Sağlık',
  'vitamin': 'Sağlık',
  'ilaç': 'Sağlık',
  'eczane': 'Sağlık',
  'medikal': 'Sağlık',
  'diş bakımı': 'Sağlık',
  'tıbbi cihaz': 'Sağlık',
  'ağırlık & tansiyon': 'Sağlık',
  // ── Otomotiv ─────────────────────────────────────────────────────
  'otomotiv': 'Otomotiv',
  'oto': 'Otomotiv',
  'otomotiv & motosiklet': 'Otomotiv',
  'araç': 'Otomotiv',
  'araba aksesuar': 'Otomotiv',
  'oto aksesuar': 'Otomotiv',
  'lastik': 'Otomotiv',
  'motosiklet': 'Otomotiv',
  'akü & elektrik': 'Otomotiv',
  'araç bakım': 'Otomotiv',
  // ── Pet Shop ─────────────────────────────────────────────────────
  'pet': 'Pet Shop',
  'pet shop': 'Pet Shop',
  'evcil hayvan': 'Pet Shop',
  'kedi': 'Pet Shop',
  'köpek': 'Pet Shop',
  'kuş': 'Pet Shop',
  'akvaryum': 'Pet Shop',
  // ── Bahçe & Yapı ─────────────────────────────────────────────────
  'bahçe': 'Bahçe & Yapı',
  'bahçe & yapı': 'Bahçe & Yapı',
  'yapı': 'Bahçe & Yapı',
  'yapı market': 'Bahçe & Yapı',
  'hırdavat': 'Bahçe & Yapı',
  'el aleti': 'Bahçe & Yapı',
  'elektrik malzemesi': 'Bahçe & Yapı',
  'sulama': 'Bahçe & Yapı',
  'tarım': 'Bahçe & Yapı',
};

// ── Keyword fallback: if no exact match, check if raw contains a keyword ──────
// Order matters — more specific checks first.
const KEYWORD_RULES: Array<{ keywords: string[]; category: string }> = [
  { keywords: ['bilgisayar', 'tablet', 'laptop', 'notebook', 'televizyon', 'tv ', ' tv', 'kulaklık', 'drone', 'kamera', 'fotoğraf', 'yazıcı', 'monitör', 'router', 'modem', 'gaming', 'elektronik', 'telefon', 'klima'], category: 'Teknoloji' },
  { keywords: ['çamaşır makine', 'bulaşık makine', 'buzdolabı', 'davlumbaz', 'büyük ev aletleri'], category: 'Beyaz Eşya' },
  { keywords: ['oyun konsol', 'playstation', 'xbox', 'nintendo', 'oyuncak', 'lego'], category: 'Oyun & Oyuncak' },
  { keywords: ['mobilya', 'koltuk', 'kanepe', 'yatak odası', 'oturma odası', 'ofis mobilya', 'raf & kitaplık'], category: 'Mobilya & Dekorasyon' },
  { keywords: ['ayakkabı', 'valiz', 'bavul'], category: 'Ayakkabı & Çanta' },
  { keywords: ['çanta', 'cüzdan', 'sırt çanta'], category: 'Ayakkabı & Çanta' },
  { keywords: ['giyim', 'moda', 'elbise', 'pantolon', 'gömlek', 'kazak', 'mont', 'ceket', 'iç giyim', 'pijama', 'mayo', 'eşofman'], category: 'Giyim & Moda' },
  { keywords: ['parfüm', 'deodorant', 'cilt bakım', 'yüz bakım', 'saç bakım', 'makyaj', 'kozmetik', 'kişisel bakım', 'tıraş', 'güneş'], category: 'Kozmetik & Bakım' },
  { keywords: ['fitness', 'spor', 'outdoor', 'kamp', 'bisiklet', 'scooter', 'koşu'], category: 'Spor & Outdoor' },
  { keywords: ['bebek', 'çocuk', 'anne'], category: 'Anne & Bebek' },
  { keywords: ['kitap', 'kırtasiye', 'hobi', 'müzik aleti', 'sanat malzeme'], category: 'Kitap & Kırtasiye' },
  { keywords: ['süpermarket', 'market', 'gıda', 'atıştırmalık', 'kahve', 'çay'], category: 'Süpermarket' },
  { keywords: ['uçak', 'otel', 'tatil', 'seyahat', 'tur '], category: 'Seyahat' },
  { keywords: ['restoran', 'fast food', 'kafe', 'pizza', 'yemek sipariş'], category: 'Yemek & İçecek' },
  { keywords: ['vitamin', 'ilaç', 'eczane', 'medikal', 'diş bakım', 'sağlık'], category: 'Sağlık' },
  { keywords: ['otomotiv', 'motosiklet', 'lastik', 'oto aksesuar', 'araç bakım', 'akü'], category: 'Otomotiv' },
  { keywords: ['evcil', 'kedi mama', 'köpek mama', 'akvaryum'], category: 'Pet Shop' },
  { keywords: ['bahçe', 'yapı market', 'hırdavat', 'el aleti', 'sulama', 'tarım'], category: 'Bahçe & Yapı' },
  { keywords: ['mutfak', 'ev & yaşam', 'ev yaşam', 'tekstil', 'nevresim', 'perde', 'halı', 'banyo', 'aydınlatma', 'temizlik', 'depolama', 'sofra'], category: 'Ev & Yaşam' },
  { keywords: ['dekorasyon', 'ev dekora'], category: 'Mobilya & Dekorasyon' },
];

export function normalizeCategory(raw: string): string {
  if (!raw) return 'Ev & Yaşam';
  const trimmed = raw.trim();
  const key = trimmed.toLowerCase();

  // 1. Exact map lookup
  const exact = EXACT_MAP[key];
  if (exact) return exact;

  // 2. Keyword-contains fallback (space-padded to avoid partial word collisions)
  const padded = ` ${key} `;
  for (const rule of KEYWORD_RULES) {
    if (rule.keywords.some(kw => padded.includes(kw))) {
      return rule.category;
    }
  }

  // 3. If the raw value is already a known CATEGORIES entry (e.g. submitted manually)
  if (CATEGORIES.includes(trimmed)) return trimmed;

  // 4. Unknown — show in Tümü only
  if (__DEV__) {
    console.log(`[category] unmapped: "${trimmed}"`);
  }
  return 'Diğer';
}
