export const CATEGORIES = [
  'Teknoloji',
  'Beyaz Eşya',
  'Giyim & Moda',
  'Ayakkabı & Çanta',
  'Ev & Yaşam',
  'Mobilya & Dekorasyon',
  'Spor & Outdoor',
  'Kozmetik & Bakım',
  'Süpermarket',
  'Anne & Bebek',
  'Kitap & Kırtasiye',
  'Oyun & Oyuncak',
  'Seyahat',
  'Yemek & İçecek',
  'Sağlık',
  'Otomotiv',
  'Pet Shop',
  'Bahçe & Yapı',
];

export const CATEGORIES_WITH_OTHER = [...CATEGORIES, 'Diğer'];

const CATEGORY_NORMALIZE_MAP: Record<string, string> = {
  'ev': 'Ev & Yaşam',
  'ev & yaşam': 'Ev & Yaşam',
  'ev, yaşam & mutfak': 'Ev & Yaşam',
  'ev yaşam': 'Ev & Yaşam',
  'ev ve yaşam': 'Ev & Yaşam',
  'mutfak': 'Ev & Yaşam',
  'ev aletleri': 'Ev & Yaşam',
  'elektronik': 'Teknoloji',
  'teknoloji': 'Teknoloji',
  'cep telefonu': 'Teknoloji',
  'bilgisayar': 'Teknoloji',
  'beyaz eşya': 'Beyaz Eşya',
  'giyim': 'Giyim & Moda',
  'giyim & moda': 'Giyim & Moda',
  'giyim & ayakkabı': 'Giyim & Moda',
  'moda': 'Giyim & Moda',
  'ayakkabı': 'Ayakkabı & Çanta',
  'ayakkabı & çanta': 'Ayakkabı & Çanta',
  'çanta': 'Ayakkabı & Çanta',
  'mobilya': 'Mobilya & Dekorasyon',
  'mobilya & dekorasyon': 'Mobilya & Dekorasyon',
  'dekorasyon': 'Mobilya & Dekorasyon',
  'spor': 'Spor & Outdoor',
  'spor & outdoor': 'Spor & Outdoor',
  'kozmetik': 'Kozmetik & Bakım',
  'kozmetik & bakım': 'Kozmetik & Bakım',
  'kozmetik & kişisel bakım': 'Kozmetik & Bakım',
  'kişisel bakım': 'Kozmetik & Bakım',
  'süpermarket': 'Süpermarket',
  'market': 'Süpermarket',
  'gıda': 'Süpermarket',
  'bebek': 'Anne & Bebek',
  'anne & bebek': 'Anne & Bebek',
  'anne bebek': 'Anne & Bebek',
  'kitap': 'Kitap & Kırtasiye',
  'kitap & kırtasiye': 'Kitap & Kırtasiye',
  'kırtasiye': 'Kitap & Kırtasiye',
  'oyuncak': 'Oyun & Oyuncak',
  'oyun & oyuncak': 'Oyun & Oyuncak',
  'oyun': 'Oyun & Oyuncak',
  'seyahat': 'Seyahat',
  'seyahat & turizm': 'Seyahat',
  'yemek': 'Yemek & İçecek',
  'yemek & içecek': 'Yemek & İçecek',
  'içecek': 'Yemek & İçecek',
  'sağlık': 'Sağlık',
  'otomotiv': 'Otomotiv',
  'oto': 'Otomotiv',
  'otomotiv & motosiklet': 'Otomotiv',
  'araç': 'Otomotiv',
  'pet': 'Pet Shop',
  'pet shop': 'Pet Shop',
  'evcil hayvan': 'Pet Shop',
  'bahçe': 'Bahçe & Yapı',
  'bahçe & yapı': 'Bahçe & Yapı',
  'yapı': 'Bahçe & Yapı',
};

export function normalizeCategory(raw: string): string {
  if (!raw) return 'Ev & Yaşam';
  const key = raw.trim().toLowerCase();
  return CATEGORY_NORMALIZE_MAP[key] ?? raw;
}
